-- Add org-scoped forecast columns (Company and Plant as RFC scope)
ALTER TABLE "Forecast" ADD COLUMN "companyId" TEXT;
ALTER TABLE "Forecast" ADD COLUMN "plantId"   TEXT;

ALTER TABLE "Forecast"
  ADD CONSTRAINT "Forecast_companyId_fkey"
  FOREIGN KEY ("companyId") REFERENCES "Company"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Forecast"
  ADD CONSTRAINT "Forecast_plantId_fkey"
  FOREIGN KEY ("plantId") REFERENCES "Plant"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

-- Add closing-date and auto-generated flag to Version
ALTER TABLE "Version" ADD COLUMN "closingDate"     TIMESTAMP(3);
ALTER TABLE "Version" ADD COLUMN "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- Backfill sequence default (existing rows already have a value; this is a safety net)
UPDATE "Version" SET "sequence" = 'A' WHERE "sequence" IS NULL OR "sequence" = '';
